fix(table): always update table pages after data has been updated or loaded
This fixes an issue where we saw an uncaught exception in the dev
console:

```
Error: Uncaught (in promise): [object Undefined]
```

After some research we found out that it came from the `setMaxPage` call
to tabulator. We never concluded why it happened but it seems that the
problem was that tabulator was already doing a ajax request.

Now we have changed such that setMaxPage is called after the data has
been loaded and that seems to have solved the issue. ...fingers crossed
;)